service: subcity-webhook

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 3003
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: ${opt:stage, "dev"}
  environment: ${file(../env.yml):${opt:stage, "dev"}}

  iamRoleStatements:
    - Effect: Allow
      Action:
        # - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:*"

functions:

  ### Inbound Webhooks

  inbound:
    handler: handler.inbound
    events:
      - http:
          path: /
          method: post
          cors: true